org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=ic2mekradfix
mod_name=IC2 Mekanism GregTech Radiation Suit Compat
mod_license=MIT
mod_version=1.2.0
mod_group_id=com.sxcccccccc.ic2mekradfix
mod_authors=SXCCCCCCCC
mod_description=Cross-compat between IC2, Mekanism and GregTech radiation protection suits: full IC2 hazmat suit (or IC2 quantum armor) and full GregTech hazmat/QuarkTech PPE suit block Mekanism radiation intake; full Mekanism hazmat suit (or MekaSuit with radiation shielding units) and full GregTech PPE suit block IC2 radiation from radioactive inventory items and nuclear reactor heat effects; full IC2 and Mekanism suits also block GregTech carcinogenic radiation.
